collegestore/schoolstore/schoolapp/urls.py
from . import views
from django.urls import path
app_name="schoolapp"
urlpatterns = [
     path('',views.home, name='home'),
     path('login/', views.login, name='login'),
     path('register/', views.register, name='register'),
     path('registerform/', views.registerform, name='registerform'),
     path('firstregister/', views.firstregister, name='firstregister'),
     path('get_json/', views.get_json, name='get_json'),

]

collegestore/schoolstore/schoolstore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('schoolapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

collegestore/schoolstore/schoolapp/models.py
from django.db import models

class Department(models.Model):
    name = models.CharField(max_length=80)
    dept = models.CharField(max_length=100)

    def __str__(self):
        return str(self.name)

class Course(models.Model):
    dept = models.CharField(max_length=80)
    course = models.CharField(max_length=100)

    def __str__(self):
        return str(self.course)

class Register(models.Model):
    username = models.CharField(max_length=200)
    password = models.CharField(max_length=8)

    def __str__(self):
        return str(self.username)

collegestore/schoolstore/schoolapp/forms.py
from django import forms
from .models import Person, City

class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ('name', 'birthdate', 'country', 'city')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

collegestore/schoolstore/schoolapp/views.py
from django.contrib.auth import authenticate
from django.shortcuts import render, redirect
from .models import Department, Course, Register
from django.http import JsonResponse
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

# Create your views here.
def home (request):
    return render(request,'base.html')
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}")
                return redirect('/')
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()

    return render(request,'login.html')
def register(request):
    if request.method == "POST":
        username = request.POST.get('username', )
        password = request.POST.get('password', )
        conpass = request.POST.get('conpassword',)
        if password == conpass:
            pd = Register(username=username, password=password)
            pd.save()
            return redirect('/')
        else:
            messages.error(request,'Password not match.')
    return render(request, 'register.html')
def registerform(request):
    qs=Department.objects.all()
    qs1 = Course.objects.all()
    return render(request,'registerform.html',{'qs':qs,'qs1':qs1})
def firstregister(request):
    return render(request,'firstregister.html')
def get_json(request):
    qsval = list(Department.objects.values())
    return JsonResponse({'data':qsval})

collegestore/schoolstore/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>eStartup Bootstrap Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="{% static 'https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Roboto:100,300,400,500,700|Philosopher:400,400i,700,700i' %}" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: eStartup - v4.10.0
  * Template URL: https://bootstrapmade.com/estartup-bootstrap-landing-page-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

      <div id="logo">
        <h1><a href="index.html"><span>C</span>ollege <span>S</span>tore</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
<!--        <a href="index.html"><img src="assets/img/logo.png" alt="" title="" /></a>-->
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="#hero">Home</a></li>&nbsp; &nbsp; &nbsp;
          <li><a href="{% url 'schoolapp:login' %}" class="btn btn-success">Login</a></li>
          <li><a class="nav-link scrollto" href="{% url 'schoolapp:register' %}">Register</a></li>
          <li class="dropdown"><a href="#"><span>Department</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="https://en.wikipedia.org/wiki/Computer_science_and_engineering">Computer Science</a></li>
              <li><a href="https://en.wikipedia.org/wiki/Civil_engineering">Civil</a></li>
              <li><a href="https://en.wikipedia.org/wiki/Electronic_engineering">Electronics</a></li>
              <li><a href="https://en.wikipedia.org/wiki/Mechanical_engineering">Mechanical</a></li>
              <li><a href="https://en.wikipedia.org/wiki/Electrical_engineering">Electrical</a></li>


            </ul>
          </li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero">
    <div class="hero-container" data-aos="fade-in">
      <h1>Welcome to Home</h1>
      <h2>"Learning is a treasure that will follow its owner everywhere."</h2>
      <img src="{% static 'assets/img/school-icon.png' %}" alt="Hero Imgs" data-aos="zoom-out" data-aos-delay="100">

  </section><!-- End Hero Section -->

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

collegestore/schoolstore/templates/firstregister.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<style>
  body{
  background-color:green;
  }
  .pos{
  padding-top:100px;
  }

</style>
    <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

</head>
<body>
<section id="hero">
    <div class="hero-container" data-aos="fade-in">
      <h1>Click here for Registration Form</h1>
        <a class="btn btn-danger" href="{% url 'schoolapp:registerform' %}">Registration Form</a>
    </div>
</section>

</body>
</html>

collegestore/schoolstore/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-form-title" style="background-image: url({% static 'images/login.jpg' %});">
					<span class="login100-form-title-1">
						Sign In
					</span>
				</div>

				<form  method='POST' class="login100-form validate-form">
					{% csrf_token %}
					<div class="wrap-input100 validate-input m-b-26" data-validate="Username is required">
						<span class="label-input100">Username</span>
						<input class="input100" type="text" name="username" placeholder="Enter username">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input m-b-18" data-validate = "Password is required">
						<span class="label-input100">Password</span>
						<input class="input100" type="password" name="password" placeholder="Enter password">
						<span class="focus-input100"></span>
					</div>

					<div class="flex-sb-m w-full p-b-30">

						<div style="float:right;">
							<a href="{% url 'schoolapp:register' %}" class="txt1">
								New Register
							</a>
						</div>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn"  >
							<a href="{% url 'schoolapp:firstregister' %}">Login</a>
						</button>
					</div>
				</form>
				{% for msg in messages %}
				<h2 style="color:red">{{msg}}</h2>
				{% endfor %}
			</div>
		</div>
	</div>

<!--===============================================================================================-->
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/main1.js' %}"></script>

</body>
</html>

collegestore/schoolstore/templates/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Au Register Forms by Colorlib</title>

    <!-- Icons font CSS-->
    <link href="{% static 'vendor1/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor1/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="{% static 'vendor1/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor1/datepicker/daterangepicker.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'css1/main.css' %}" rel="stylesheet" media="all">
</head>

<body>
    <div class="page-wrapper bg-gra-03 p-t-45 p-b-50">
        <div class="wrapper wrapper--w790">
            <div class="card card-5">
                <div class="card-heading">
                    <h2 class="title">Registration (Part1)</h2>
                </div>
                <div class="card-body">
                    <form method="POST" action="">
                        	{% csrf_token %}
                        <div class="form-row">
                            <div class="name">Username</div>
                            <div class="value">
                                <div class="input-group">
                                    <input class="input--style-5" type="text" name="username" required>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="name">Password</div>
                            <div class="value">
                                <div class="input-group">
                                    <input class="input--style-5" type="password" name="password" required>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="name">Confirm Password</div>
                            <div class="value">
                                <div class="input-group">
                                    <input class="input--style-5" type="password" name="conpassword" required>
                                </div>
                            </div>
                        </div>

                          <a href="{% url 'schoolapp:login' %}">  <button class="btn btn--radius-2 btn--red" type="submit">Register</button> </a>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Jquery JS-->
    <script src="{% static 'vendor1/jquery/jquery.min.js' %}"></script>
    <!-- Vendor JS-->
    <script src="{% static 'vendor1/select2/select2.min.js' %}"></script>
    <script src="{% static 'vendo1r/datepicker/moment.min.js' %}"></script>
    <script src="{% static 'vendor1/datepicker/daterangepicker.js' %}"></script>

    <!-- Main JS-->
    <script src="{% static 'js1/global.js' %}"></script>


{% if messages %}
    {% for message in messages %}
        {% if message.tags %} <script>alert("{{message}}")</script> {% endif %}
          {% endfor %}
{% endif %}




</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>
<!-- end document-->

collegestore/schoolstore/templates/registerform.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form by Colorlib</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'fonts2/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css2/style.css' %}">
<!--    <script>-->
<!--var subjectObject = {-->
<!--  "Computer Science": {-->
<!--    "BCA",-->
<!--    "MCA",-->
<!--    "BSc"-->
<!--  },-->
<!--  "Commerce": {-->
<!--    "BBA",-->
<!--    "BCom"-->
<!--  }-->
<!--}-->
<!--window.onload = function() {-->

<!--  var subjectSel = document.getElementById("dept");-->
<!--  var topicSel = document.getElementById("course");-->
<!--  for (var x in subjectObject) {-->
<!--    subjectSel.options[subjectSel.options.length] = new Option(x, x);-->
<!--  }-->
<!--  subjectSel.onchange = function() {-->
<!--    //empty Chapters- and Topics- dropdowns-->
<!--    topicSel.length = 1;-->
<!--    //display correct values-->
<!--    for (var y in subjectObject[this.value]) {-->
<!--      topicSel.options[topicSel.options.length] = new Option(y, y);-->
<!--    }-->
<!--  }-->
<!--}-->
<!--</script>-->
</head>
<body>
    <div class="main">
        <div class="container">
            <div class="signup-content">
                <div class="signup-img">
                    <img src="{% static 'images2/signup-img.jpg' %}" alt="">
                </div>
                <div class="signup-form">
                    <form method="POST" class="register-form" id="register-form">
                        <h2>student registration form</h2>
                        <div class="form-row">
                            <div class="form-group">
                                <label for="name">Name :</label>
                                <input type="text" name="name" id="name" required/>
                            </div>
                        </div>
                         <div class="form-group">
                            <label for="birth_date">DOB :</label>
                            <input type="date" name="birth_date" id="birth_date">
                         </div>

                        <div class="form-radio">
                            <label for="gender" class="radio-label">Gender :</label>
                            <div class="form-radio-item">
                                <input type="radio" name="gender" id="male" checked>
                                <label for="male">Male</label>
                                <span class="check"></span>
                            </div>
                            <div class="form-radio-item">
                                <input type="radio" name="gender" id="female">
                                <label for="female">Female</label>
                                <span class="check"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="phone">Phone Number :</label>
                            <input type="text" name="phone" id="phone" required/>
                        </div>
                        <div class="form-group">
                            <label for="email">Email :</label>
                            <input type="email" name="email" id="email" required/>
                        </div>
                        <div class="form-group">
                            <label for="address">Address :</label>
                            <input type="text" name="address" id="address" required/>
                        </div>
                        <div class="form-row">
                            <div class="form-group">
                                <label for="dept">Department :</label>
                                <div class="form-select" >
                                    <select name="dept" id="dept" onchange="myFunction()">
                                        <option value="" selected="selected">Select Department</option>
                                      {% for dept in qs %}
                                        <option class="item" value="{{dept}}">{{dept.name}}</option>
                                        {% endfor %}
                                    </select>
                                    <span class="select-icon"><i class="zmdi zmdi-chevron-down"></i></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="course">Course :</label>
                                <div class="form-select">
                                    <select name="course" id="course">
                                        <option value="" selected="selected">Select Course</option>
<!--                                        {% for course in qs1 %}-->
<!--                                        <option class="item" value="{{course}}">{{course.course}}</option>-->
<!--                                        {% endfor %}-->
                                    </select>
                                    <span class="select-icon"><i class="zmdi zmdi-chevron-down"></i></span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="purpose">Purpose:</label>
                            <div class="form-select">
                                <select name="purpose" id="purpose">
                                    <option value=""></option>
                                    <option value="enquiry">Enquiry</option>
                                    <option value="order">Place Order</option>
                                    <option value="Return">Return</option>
                                </select>
                                <span class="select-icon"><i class="zmdi zmdi-chevron-down"></i></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="materials">Materials:</label>
                            <div><label >debit Note Book:</label>
                            <input type="checkbox" value="debit Note Book"  name="check1" id="check1" /></div>
                            <div><label >Pen:</label>
                            <input type="checkbox" value="Pen"  name="check2" id="check2" /></div>
                           <div> <label >Exam paper:</label>
                            <input type="checkbox" value="Exam paper"  name="check3" id="check3" /></div>


                        </div>

                        <div class="form-submit">
                           <a href="{% url 'schoolapp:home' %}"> <input type="submit" value="LOG OUT" class="submit" name="logout" id="logout" /></a>
                            <input type="submit" value="SUBMIT" class="submit" name="submit" id="submit" onclick="msg()" />
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

    <!-- JS -->
    <script src="{% static 'vendor2/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js2/main.js' %}"></script>


  </form>

<script>
function myFunction() {
  var dept = document.getElementById("dept").value;
    if(dept=='Computer Science')
    { var output = [];
    output.push('<option value="BCA">BCA</option>');
    output.push('<option value="MCA">MCA</option>');
    $('#course').html(output.join(''));
    }
    if(dept=='Commerce')
    {
    var output = [];
    output.push('<option value="BCOM">B.Com</option>');
    output.push('<option value="BBA">BBA</option>');
    $('#course').html(output.join(''));
    }
}
function msg()
{
alert("Saved Successfully");
window.location.href = "http://127.0.0.1:8000/";

}
</script>
</body>

</html>
<!-- This templates was made by Colorlib (https://colorlib.com)